version: '3.8'
services:
  strava-sync:
    image: shanbs/strava-to-fittrackee:test
    network_mode: host
    volumes:
      - /opt/fittrackee/strava-to-fittrackee-secrets/_data:/app/data:ro
    restart: unless-stopped
    command: >
      bash -c "cp /app/data/.strava.tokens.json /app/;
               cp /app/data/.fittrackee.tokens.json /app/;
               while true; do bash run_sync.sh; sleep 3600; done"
    environment:
      - FITTRACKEE_HOST=127.0.0.1
      - FITTRACKEE_PORT=5001
      - POSTGRES_HOST=172.24.0.2
      - POSTGRES_PASSWORD=mysecretpassword