version: '3.8'
services:
  strava-sync:
    image: shanbs/strava-to-fittrackee:test
    network_mode: host
    volumes:
      - /opt/fittrackee/strava-to-fittrackee-secrets/_data/.strava.tokens.json:/app/.strava.tokens.json:ro
      - /opt/fittrackee/strava-to-fittrackee-secrets/_data/.fittrackee.tokens.json:/app/.fittrackee.tokens.json:ro
      - /opt/fittrackee/strava-to-fittrackee-secrets/_data/.env:/app/.env:ro
    restart: unless-stopped
    command: ["bash", "run_sync.sh"]
    environment:
      - FITTRACKEE_HOST=127.0.0.1
      - FITTRACKEE_PORT=5001
      - POSTGRES_HOST=172.24.0.2
      - POSTGRES_PASSWORD=mysecretpassword