version: '3.8'
services:
  strava-sync:
    build: .
    volumes:
      - /mnt/data/docker/volumes/strava-to-fittrackee-secrets/_data/.env:/app/.env:ro
      - /mnt/data/docker/volumes/strava-to-fittrackee-secrets/_data/.strava.tokens.json:/app/.strava.tokens.json
      - /mnt/data/docker/volumes/strava-to-fittrackee-secrets/_data/.fittrackee.tokens.json:/app/.fittrackee.tokens.json
    restart: unless-stopped
    command: ["bash", "run_sync.sh"]
    environment:
      - FITTRACKEE_DB_HOST=fittrackee_db